server:
  port: 11000


spring:
  application:
    name: shop-centre-eureka-service
  freemarker:
      template-loader-path: classpath:/templates/
      prefer-file-system-access: false
  boot:
      admin:
        client:
          url: http://${eureka.instance.hostname}:11020/
          username: admin
          password: admin

eureka:
  client:
    # 是否注册到eureka
    registerWithEureka: false
    # 是否从eureka获取注册信息
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: shop-centre.com
    #显示IP
    prefer-ip-address: true
    #注册实例 Status 名称 自定义服务名称
    instance-id: ${spring.application.name}:${server.port}

# 环境配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#info 信息
info:
  app:
    #从pom.xml中获取
    name: "@project.name@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
    groupId: "@project.groupId@"
    artifactId: "@project.artifactId@"
    packaging: "@project.packaging@"
    description: "@project.description@"
    href: "@project.url@"
    port: ${server.port}
    url: ${eureka.instance.hostname}:${server.port}